name: Build Nginx on FreeBSD (GitHub Actions)

on:
  push:
    branches: [ main ]  # 修改为你自己的主分支
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为编译环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config wget tar gzip libpcre3-dev zlib1g-dev libssl-dev

      - name: Download Nginx Source
        run: |
          wget http://nginx.org/download/nginx-1.24.0.tar.gz  # 使用最新稳定版本
          tar -zxvf nginx-1.24.0.tar.gz
          cd nginx-1.24.0

      - name: Configure Nginx
        run: |
          cd nginx-1.24.0
          ./configure --prefix=/tmp/nginx_build \
            --with-pcre \
            --with-zlib \
            --with-openssl \
            --without-http_rewrite_module \
            --without-http_gzip_module \
            --without-http_proxy_module

      - name: Build Nginx
        run: |
          cd nginx-1.24.0
          make

      - name: Package Nginx
        run: |
          cd nginx-1.24.0
          make install

      - name: Create Tar Archive
        run: |
          cd /tmp
          tar -czvf nginx_freebsd.tar.gz nginx_build  # 将 nginx_build 目录打包

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nginx_freebsd
          path: /tmp/nginx_freebsd.tar.gz
